### ISSUE TITLE
`npx git-rebase-branches` fails

### ISSUE THREAD

**Issue by Turbo87** [balena-io-modules/git-rebase-branches#3]
```
$ npx git-rebase-branches
Cannot find module '../build'
Require stack:
- /Users/tbieniek/.npm/_npx/73952/lib/node_modules/git-rebase-branches/bin/git-rebase-branches
```

it looks like the published `git-rebase-branches` package only has a `src` folder, but no `build.js` file (see https://unpkg.com/browse/git-rebase-branches@0.3.0/)

**Comment by thgreasi** [comment]
Thanks for reporting this @Turbo87 .
Trying this with `npm link` is probably the reason I didn't notice.
#4 resolved this issue.
